name: Weekly Catalog Export

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Export catalog data
      run: make catalog
